### PR TITLE
Reorganizing directory structure and minor housekeeping

### PR DESCRIPTION
**Pull request by k4yt3x**
The motivation for making these changes is mainly to cleanup the current repository's root directory. Currently, a lot of the `.h`, `.cpp`, config, and script files are scattered in the root directory of the repository. I've sorted all files into appropriate repositories (e.g., all source code went to `/src`) so it's less of a hassle to find specific types of files and the repo just looks cleaner.

I've tested and the build works correctly, so does the pipeline.

Aside from the reorganization, I've also done some minor changes like updating and formatting the README file. The changes should be easy to tell from the commits and diff below.

### CODE REVIEW

**Comment by gatekeep** [comment]
This is a significant change, as such per our policies will require review from the entire team.

Here are my thoughts on this:
- The "debian" directory does not belong in "src" (it is not a source code bearing directory and is important to remain in root as part of the debian package build chain) and should be within the project root.
- I feel it unnecessary to separate the scripts into a "scripts" directory, and preferably would like to keep those in the project root.
- I don't care for the movement of the example configuration files to an "examples" directory (I typically reserve examples as a directory to contain example code and not example/sample configuration files), and I would prefer they remain in the project root.
- I'd prefer to continue to utilize the Markdown version of the license. I do not see any particular reason why this was changed, plenty of other projects utilize the plain-text or markdown equivalents. (In this regard do not use the company line of "conventions").

**Comment by k4yt3x** [comment]
- I agree the debian dir should be moved back to root.
- It's standard practice to have the scripts in its own repository. These scripts are optional. One can use either scripts to launch it interactively, use an init script to launch it with SysV init, or use a systemd service unit to start it with systemd. In fact, I've never used the start/stop scripts and have always just launched it from command line. As the number of scripts will only grow, it'll be a mess if all of them are in repo root.
- The number of config files will grow, and it'll become difficult to tell which config files need to be copied during installation. It also makes it easier for installation scripts and packaging tools as you only have to copy everything under examples or configs. It can be renamed to conf or configs. I'm also thinking where should be a good place to upload the systemd unit files I wrote.
- I changed the LICENSE.md to LICENSE just because it's the GitHub standard practice. We can delete that commit if necessary. It doesn't matter too much from a readability/legality standpoint. I just wanted it to look the same as the GH standard.

**Comment by k4yt3x** [comment]
>     * The current situation works for all of the developers at hand, and seeing as this is still quite frankly a _small_ project, reorganizing simply for the thought of "standardization" is a bit excessive.

I really don't think this project is "small." To maintain the quality of the code and thus ensuring the stability, readability, and the ease of contribution, I see it necessary to follow standards.

>     * I also find it unreasonable to add yourself to the developers section for a change so minor as an unrequested reorganization of the project, even with existing efforts to redo the build chain. That should come with significant contributions to the project.

I just added it when I was formatting the Markdown files. You can remove it if you find it unreasonable. I'm helping more than just this PR though, but honestly I don't care if I'm in the file.

**Comment by gatekeep** [comment]
> * I agree the debian dir should be moved back to root.
> * It's standard practice to have the scripts in its own repository. These scripts are optional. One can use either scripts to launch it interactively, use an init script to launch it with SysV init, or use a systemd service unit to start it with systemd. In fact, I've never used the start/stop scripts and have always just launched it from command line. As the number of scripts will only grow, it'll be a mess if all of them are in repo root.
> * The number of config files will grow, and it'll become difficult to tell which config files need to be copied during installation. It also makes it easier for installation scripts and packaging tools as you only have to copy everything under examples or configs. It can be renamed to conf or configs. I'm also thinking where should be a good place to upload the systemd unit files I wrote.
> * I changed the LICENSE.md to LICENSE just because it's the GitHub standard practice. We can delete that commit if necessary. It doesn't matter too much from a readability/legality standpoint. I just wanted it to look the same as the GH standard.

- Entirely fair response on the scripts directory, however, if moving these there then changes to the CMakeFiles.txt will have to be done to account for that change. The iden_channel_calc.py script however, should be in the project root, it is not an installed script.
- As far as the configuration files, we should then perhaps, consider another standard convention for placement of these files.

**Comment by gatekeep** [comment]
> > Entirely fair response on the scripts directory, however, if moving these there, then changes to the CMakeFiles.txt will have to be done to account for that movement. Additionally, the iden_channel_calc.py script however, should be in the project root, it is not an installed script.
> 
> Yeah the CMakeFiles will have to be updated. I suck at CMake so I only changed the compilation part so it compiles. The installation part should look like what I shared in Discord yesterday, and I think there's still quite a bit of work there. We can patch it enough so it will work for now, but more changes will have to come later.
> 
> On the topic of the iden script, I was gonna talk about that in the group. I rewrote that script so it's now a Python package installable through Pip. I think there is no point keeping it in the repo anymore if you're fine with the [new script](https://github.com/k4yt3x/iden-channel-calculator).
> 
> > As far as the configuration files, we should then perhaps, consider another standard convention for placement of these files. And such movement of these files will have to be accounted for, again, within CMakeFiles.txt.
> 
> I concur.

- I suggest putting these scripts within a directory named "tools".
- I suggest putting the configuration files within a directory either named "etc" or "config".

Please update this PR with commits changing that, along with putting the debian directory back in project root.

**Comment by k4yt3x** [comment]
Since I didn't find a definitive answer for standard project layout for C++ (just like everything else in C++), I recommend that we follow the standard [GO project layout](https://github.com/golang-standards/project-layout) and name the directories `tools` and `configs`. How does that work for you?

**Comment by gatekeep** [comment]
> Since I didn't find a definitive answer for standard project layout for C++ (just like everything else in C++), I recommend that we follow the standard [GO project layout](https://github.com/golang-standards/project-layout) and name the directories `tools` and `configs`. How does that work for you?

This is fine and in-line with my original request for PR update.

**Comment by k4yt3x** [comment]
PR updated.

**Review by gatekeep — CHANGES_REQUESTED** [review]
Final changes and this should be good by me.

**Review by gatekeep — APPROVED** [review]
Looks good to me, this just awaits review from the others.

**Review by majmongoose — APPROVED** [review]
Looks okay to me.

**Comment by jelimoore** [comment]
I am OK with these changes as of now.

**Pull request merged**
