### PR TITLE
Fixed incorrect channel spacing sanity check

### PR DESCRIPTION
**Pull request by faultywarrior**

### CODE REVIEW

**Review by gatekeep — COMMENTED** [review]
Looks okay.

**Comment by gatekeep** [comment]
Did you test these changes? Did it resolve the problem?

**Comment by faultywarrior** [comment]
Tested and confirmed it fixes the problem.  Also updated the comments with the second commit to match the new values.

**Review by gatekeep — APPROVED** [review]
LGTM.

**Pull request merged**
